[workspace]
members = ["crates/moss-cli", "crates/moss-precompiler"]
resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
libc = "0.2"
sha2 = "0.10"
wasmtime = "45"
wasmtime-wasi = "45"

[profile.release-with-debug]
inherits = "release"
debug = true
