"""Generators for the parts of the self-hosted compiler that are tables.

Three files under `src/` are mechanical: the spelling of every string the
compiler must hold itself ([D48]), the token kinds as Ints, and the `Wasm`
context as an opcode table. Writing any of them by hand is a typo per
character, so they are generated here and checked against disk by
tests/test_gensrc.py — the arrangement lib/char.moss already has with
mossc.native.
"""

import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]

# `char::` constant names for the characters that are not their own name.
CHAR_NAME = {"_": "underscore", ".": "dot"}
for _d in range(10):
    CHAR_NAME[str(_d)] = f"digit{_d}"


def _nibble(value: int) -> str:
    return {0: "zero", 1: "one"}.get(value, f"n{value}()")


def _number(value: int) -> str:
    """A small Int, built from `zero` and `one` (D4): a byte is its two
    nibbles, which is how a Wasm opcode is spelled in the specification."""
    if value < 16:
        return _nibble(value)
    return f"hex({_nibble(value >> 4)}, {_nibble(value & 15)})"


# --- src/spell.moss ---------------------------------------------------

# Names the compiler cannot read out of a file: what a Wasm module calls
# its imports and exports, and the handful it must recognize by spelling.
SPELLED = [
    "wasi_snapshot_preview1",
    "fd_write",
    "fd_read",
    "fd_close",
    "args_get",
    "args_sizes_get",
    "path_open",
    "proc_exit",
    "_start",
    "memory",
    "main",
    "wasm.moss",
    "wasip1.moss",
    "I32",
    "I64",
    "bool.moss",
    "wasistd.moss",
    "i32_bool",
    "Bool",
    "true",
    "false",
    "True",
    "False",
]


def gen_spell_moss() -> str:
    out = ['''import "./bytes.moss" use push_char;

# The strings the compiler must hold itself.
#
# A Wasm module names its imports and exports in its own bytes, so an
# emitter cannot avoid knowing how `wasi_snapshot_preview1` is spelled,
# and the back end cannot recognize `I32` or `i32_bool` without knowing
# how those are spelled either. There are no string literals (D48), so
# each one is written character by character against the `char`
# constants — the same technique the lexer's keyword trie uses to
# recognize keywords without literals. This is the whole of what D48
# costs the back end: one function per name, and no name the compiler
# does not already need appears here.
#
# Generated by bootstrap/mossc/gensrc.py; regenerate rather than edit.

assume Std {''']
    for name in SPELLED:
        fn = "sp_" + name.replace(".", "_").lstrip("_")
        pushes = "\n".join(
            f"    push_char(out, char::{CHAR_NAME.get(c, c)});" for c in name
        )
        out.append(f"  fn {fn}(out: IntList) {{\n{pushes}\n  }}\n")
    out.append("}")
    return "\n".join(out) + "\n"


# --- src/tcode.moss ---------------------------------------------------

TOKEN_SNAKE = {
    "LParen": "lparen",
    "RParen": "rparen",
    "LBracket": "lbracket",
    "RBracket": "rbracket",
    "LBrace": "lbrace",
    "RBrace": "rbrace",
    "ThisType": "this_type",
    "ThisValue": "this_value",
}


def _snake(name: str) -> str:
    if name in TOKEN_SNAKE:
        return TOKEN_SNAKE[name]
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def token_names() -> list:
    source = (REPO / "src/lex.moss").read_text(encoding="utf-8")
    match = re.search(r"type Token =(.*?);", source, re.S)
    return [part.strip() for part in match.group(1).split("|") if part.strip()]


def gen_tcode_moss() -> str:
    names = token_names()
    out = ['''import "./bytes.moss" use *;
import "./lex.moss" use Token;
import "./token.moss" use *;

# Token kinds as Ints.
#
# `Token` is a union of sixty units, which is the right type for the
# lexer to return and the wrong one for a recursive-descent parser to
# carry: a parser compares the current token against a handful of
# expected ones per production, and a match arm per comparison is
# unreadable. The cursor holds an Int instead, converted here once per
# token.
#
# Generated by bootstrap/mossc/gensrc.py; regenerate rather than edit.

assume Std {''']
    for i, name in enumerate(names):
        out.append(f"  fn tk_{_snake(name)}(): Int {{ {_number(i)} }}")
    out.append("")
    out.append("  fn token_code(t: Token): Int {")
    out.append("    match t {")
    for name in names:
        out.append(f"      {name} => tk_{_snake(name)}(),")
    out.append("    }")
    out.append("  }")
    out.append("}")
    return "\n".join(out) + "\n"


# --- src/wasmops.moss -------------------------------------------------

SIMPLE, MEMARG, CONST0, CONST1, MEMZERO, MEMCOPY, MEMFILL = range(7)
NONE, I32, I64 = 0, 1, 2

KIND_FN = {
    SIMPLE: "wk_simple()",
    MEMARG: "wk_memarg()",
    CONST0: "wk_const0()",
    CONST1: "wk_const1()",
    MEMZERO: "wk_memzero()",
    MEMCOPY: "wk_memcopy()",
    MEMFILL: "wk_memfill()",
}
RES_FN = {NONE: "wr_none()", I32: "wr_i32()", I64: "wr_i64()"}

COMPARISONS = "eqz eq ne lt_s lt_u gt_s gt_u le_s le_u ge_s ge_u".split()
ARITHMETIC = (
    "clz ctz popcnt add sub mul div_s div_u rem_s rem_u and or xor shl"
    " shr_s shr_u rotl rotr"
).split()


def wasm_ops() -> dict:
    """name -> (opcode, encoding, alignment, result). Mirrors WASM_OPS in
    mossc/build.py; the two back ends must select the same instruction."""
    ops = {}

    def add(name, code, kind=SIMPLE, align=0, res=I32):
        ops[name] = (code, kind, align, res)

    add("unreachable", 0x00, SIMPLE, 0, NONE)
    add("i32_zero", 0, CONST0, 0, I32)
    add("i32_one", 0, CONST1, 0, I32)
    for name, code, align, res in [
        ("i32_load", 0x28, 2, I32), ("i64_load", 0x29, 3, I64),
        ("i32_load8_s", 0x2C, 0, I32), ("i32_load8_u", 0x2D, 0, I32),
        ("i32_load16_s", 0x2E, 1, I32), ("i32_load16_u", 0x2F, 1, I32),
        ("i64_load8_s", 0x30, 0, I64), ("i64_load8_u", 0x31, 0, I64),
        ("i64_load16_s", 0x32, 1, I64), ("i64_load16_u", 0x33, 1, I64),
        ("i64_load32_s", 0x34, 2, I64), ("i64_load32_u", 0x35, 2, I64),
        ("i32_store", 0x36, 2, NONE), ("i64_store", 0x37, 3, NONE),
        ("i32_store8", 0x3A, 0, NONE), ("i32_store16", 0x3B, 1, NONE),
        ("i64_store8", 0x3C, 0, NONE), ("i64_store16", 0x3D, 1, NONE),
        ("i64_store32", 0x3E, 2, NONE),
    ]:
        add(name, code, MEMARG, align, res)
    add("memory_size", 0x3F, MEMZERO, 0, I32)
    add("memory_grow", 0x40, MEMZERO, 0, I32)
    add("memory_copy", 0xFC, MEMCOPY, 0, NONE)
    add("memory_fill", 0xFC, MEMFILL, 0, NONE)
    for i, name in enumerate(COMPARISONS):
        add(f"i32_{name}", 0x45 + i)
        add(f"i64_{name}", 0x50 + i)  # a comparison yields an i32
    for i, name in enumerate(ARITHMETIC):
        add(f"i32_{name}", 0x67 + i)
        add(f"i64_{name}", 0x79 + i, SIMPLE, 0, I64)
    add("i32_extend8_s", 0xC0)
    add("i32_extend16_s", 0xC1)
    add("i64_extend8_s", 0xC2, SIMPLE, 0, I64)
    add("i64_extend16_s", 0xC3, SIMPLE, 0, I64)
    add("i64_extend32_s", 0xC4, SIMPLE, 0, I64)
    add("i32_wrap_i64", 0xA7)
    add("i64_extend_i32_s", 0xAC, SIMPLE, 0, I64)
    add("i64_extend_i32_u", 0xAD, SIMPLE, 0, I64)
    return ops


def gen_wasmops_moss() -> str:
    out = ['''import "./bytes.moss" use *;
import "./intern.moss" as intern;

# The `Wasm` context, as a table the back end can match a callee against.
#
# A call to one of these compiles to an instruction rather than to a call
# (D52). Recognizing one means knowing how it is spelled, and there are
# no string literals (D48), so each name is built character by character
# and interned once — after which a lookup is a comparison of interned
# ids. The opcodes mirror bootstrap/mossc/build.py.
#
# Generated by bootstrap/mossc/gensrc.py; regenerate rather than edit.

assume Std {
  # How an intrinsic encodes.
  fn wk_simple(): Int { zero }
  fn wk_memarg(): Int { one }
  fn wk_const0(): Int { n2() }
  fn wk_const1(): Int { n3() }
  fn wk_memzero(): Int { n4() }
  fn wk_memcopy(): Int { n5() }
  fn wk_memfill(): Int { n6() }

  # What it leaves on the stack.
  fn wr_none(): Int { zero }
  fn wr_i32(): Int { one }
  fn wr_i64(): Int { n2() }

  val op_names: IntList;
  val op_codes: IntList;
  val op_kinds: IntList;
  val op_aligns: IntList;
  val op_res: IntList;

  context WasmOps = op_names, op_codes, op_kinds, op_aligns, op_res;

  assume WasmOps, intern::Interner {
    fn add_op(cs: IntList, code: Int, kind: Int, align: Int, res: Int) {
      op_names.push(intern::intern_chars(cs));
      op_codes.push(code);
      op_kinds.push(kind);
      op_aligns.push(align);
      op_res.push(res);
    }

    # The table's index for this interned name, or none.
    fn find_op(name: Int): Int {
      var i = zero;
      while i.lt(op_names.length()) {
        if op_names.get(i).eq(name) {
          return i;
        }
        i = i.add(one);
      }
      one.neg()
    }

    fn install_wasm_ops() {''']
    for name, (code, kind, align, res) in wasm_ops().items():
        buf = f"b_{name}"
        pushes = "".join(
            f" push_char({buf}, char::{CHAR_NAME.get(c, c)});" for c in name
        )
        out.append(
            f"      let {buf} = int_list();{pushes}"
            f" add_op({buf}, {_number(code)}, {KIND_FN[kind]},"
            f" {_number(align)}, {RES_FN[res]});"
        )
    out.append("    }")
    out.append("  }")
    out.append("}")
    return "\n".join(out) + "\n"


GENERATED = {
    "src/spell.moss": gen_spell_moss,
    "src/tcode.moss": gen_tcode_moss,
    "src/wasmops.moss": gen_wasmops_moss,
}


def write_all() -> None:
    for rel, generate in GENERATED.items():
        (REPO / rel).write_text(generate(), encoding="utf-8")


if __name__ == "__main__":
    write_all()
