//! Rough throughput comparison: the Rust lexer vs each WASM variant.
//!
//! Run with:  cargo test -p lexwat-test --release --test bench -- --ignored --nocapture
//!
//! Not a microbenchmark harness (no warmup statistics) — just enough to answer
//! "how does the WASM lexer compare, and does br_table matter".

use std::path::{Path, PathBuf};
use std::time::Instant;

use logos::Logos;
use moss_core::lex::Token;
use wasmtime::*;

struct Host {
    src: Vec<u8>,
    idx: usize,
}

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .unwrap()
}

/// A `.wat` source that lives alongside this crate.
fn crate_file(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join(name)
}

/// A `.wasm` artifact generated by build.rs into OUT_DIR (present only when the
/// binaryen tools were available at build time).
fn out_file(name: &str) -> PathBuf {
    Path::new(env!("OUT_DIR")).join(name)
}

/// Concatenate all `.moss` files that lex without error, repeated to ~`target` bytes.
fn corpus(target: usize) -> String {
    fn walk(dir: &Path, out: &mut Vec<String>) {
        let Ok(entries) = std::fs::read_dir(dir) else { return };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                if path.file_name().is_some_and(|n| n == "target" || n == ".git") {
                    continue;
                }
                walk(&path, out);
            } else if path.extension().is_some_and(|e| e == "moss") {
                if let Ok(text) = std::fs::read_to_string(&path) {
                    // Skip files that don't lex cleanly (the tests/errors/ corpus).
                    let clean = Token::lexer(&text).spanned().all(|(r, _)| r.is_ok());
                    if clean {
                        out.push(text);
                    }
                }
            }
        }
    }
    let mut files = Vec::new();
    walk(&repo_root(), &mut files);
    let unit = files.join("\n");
    let mut s = String::new();
    while s.len() < target {
        s.push_str(&unit);
        s.push('\n');
    }
    s
}

fn rust_token_count(src: &str) -> usize {
    Token::lexer(src).spanned().filter(|(r, _)| r.is_ok()).count() + 1
}

// logos without span tracking — closest to "just the DFA".
fn rust_token_count_nospan(src: &str) -> usize {
    Token::lexer(src).filter(|r| r.is_ok()).count() + 1
}

/// Instantiate a WASM variant once; return a closure that lexes `src` and
/// returns the token count (driving `next_byte` from a freshly reset cursor).
fn wasm_runner(
    engine: &Engine,
    wat_name: &str,
) -> impl FnMut(&str) -> usize {
    let wasm = wat::parse_file(crate_file(wat_name)).unwrap();
    let module = Module::new(engine, &wasm).unwrap();
    let mut store = Store::new(
        engine,
        Host {
            src: Vec::new(),
            idx: 0,
        },
    );
    let mut linker = Linker::new(engine);
    linker
        .func_wrap("env", "next_byte", |mut caller: Caller<'_, Host>| -> i32 {
            let h = caller.data_mut();
            match h.src.get(h.idx) {
                Some(&b) => {
                    h.idx += 1;
                    b as i32
                }
                None => -1,
            }
        })
        .unwrap();
    let instance = linker.instantiate(&mut store, &module).unwrap();
    let reset = instance.get_typed_func::<(), ()>(&mut store, "reset").unwrap();
    let next_token = instance
        .get_typed_func::<(), i32>(&mut store, "next_token")
        .unwrap();

    move |src: &str| {
        store.data_mut().src.clear();
        store.data_mut().src.extend_from_slice(src.as_bytes());
        store.data_mut().idx = 0;
        reset.call(&mut store, ()).unwrap();
        let mut count = 0usize;
        loop {
            let id = next_token.call(&mut store, ()).unwrap();
            count += 1;
            if id <= 0 {
                break;
            }
        }
        count
    }
}

/// Instantiate a module that reads its source from its own memory (no per-byte
/// import). The host writes the source at `offset` once per pass. Works for both
/// lex_selfsource.wat and the wasm-merge output (driver owns memory at offset 0).
fn wasm_mem_runner(
    engine: &Engine,
    wasm: &[u8],
    offset: usize,
) -> impl FnMut(&str) -> usize {
    let module = Module::new(engine, wasm).unwrap();
    let mut store = Store::new(engine, Host { src: Vec::new(), idx: 0 });
    // These modules have no imports (or only the now-internalized next_byte).
    let linker = Linker::new(engine);
    let instance = linker.instantiate(&mut store, &module).unwrap();
    let memory = instance.get_memory(&mut store, "memory").unwrap();
    let set_len = instance.get_typed_func::<i32, ()>(&mut store, "set_len").unwrap();
    let reset = instance.get_typed_func::<(), ()>(&mut store, "reset").ok();
    let next_token = instance
        .get_typed_func::<(), i32>(&mut store, "next_token")
        .unwrap();

    move |src: &str| {
        memory.write(&mut store, offset, src.as_bytes()).unwrap();
        if let Some(r) = &reset {
            r.call(&mut store, ()).unwrap();
        }
        set_len.call(&mut store, src.len() as i32).unwrap();
        let mut count = 0usize;
        loop {
            let id = next_token.call(&mut store, ()).unwrap();
            count += 1;
            if id <= 0 {
                break;
            }
        }
        count
    }
}

/// Runner for the two-memory `run()`-once modules (merged2 and its wasm-opt'd form).
fn run_once_runner(wasm: &[u8]) -> impl FnMut(&str) -> usize {
    let mut cfg = Config::new();
    cfg.wasm_multi_memory(true);
    let engine = Engine::new(&cfg).unwrap();
    let module = Module::new(&engine, wasm).unwrap();
    let mut store = Store::new(&engine, ());
    let instance = Linker::new(&engine).instantiate(&mut store, &module).unwrap();
    let bmem = instance.get_memory(&mut store, "bytes").unwrap();
    let tmem = instance.get_memory(&mut store, "toks").unwrap();
    let reset = instance.get_typed_func::<(), ()>(&mut store, "reset").unwrap();
    let set_len = instance.get_typed_func::<i32, ()>(&mut store, "set_len").unwrap();
    let run = instance.get_typed_func::<(), i32>(&mut store, "run").unwrap();
    let mut sink = vec![0u8; 4 << 20];
    move |src: &str| {
        bmem.write(&mut store, 0, src.as_bytes()).unwrap();
        reset.call(&mut store, ()).unwrap();
        set_len.call(&mut store, src.len() as i32).unwrap();
        let n = run.call(&mut store, ()).unwrap() as usize;
        tmem.read(&store, 0, &mut sink[..n * 4]).unwrap();
        n
    }
}

fn time<F: FnMut() -> usize>(label: &str, iters: usize, bytes: usize, mut f: F) {
    // warmup
    let _ = f();
    let start = Instant::now();
    let mut acc = 0usize;
    for _ in 0..iters {
        acc = acc.wrapping_add(f());
    }
    let dt = start.elapsed();
    let total_bytes = (bytes * iters) as f64;
    let mb_s = total_bytes / dt.as_secs_f64() / 1e6;
    let ns_tok = dt.as_secs_f64() * 1e9 / (acc as f64);
    println!(
        "  {label:<26} {mb_s:8.1} MB/s   {ns_tok:6.1} ns/token   ({:?} for {iters} iters)",
        dt
    );
}

#[test]
#[ignore]
fn dump_corpus() {
    // Used by the wasm2c+clang experiment so it lexes byte-identical input.
    let src = corpus(512 * 1024);
    std::fs::write("/tmp/corpus.bin", &src).unwrap();
    println!("wrote {} bytes to /tmp/corpus.bin", src.len());
}

#[test]
#[ignore]
fn benchmark() {
    let src = corpus(512 * 1024);
    let bytes = src.len();
    let tokens = rust_token_count(&src);
    let iters = 100;
    println!(
        "\ncorpus: {bytes} bytes, {tokens} tokens/pass, {iters} passes\n"
    );

    time("rust (logos, spanned)", iters, bytes, || rust_token_count(&src));
    time("rust (logos, no span)", iters, bytes, || rust_token_count_nospan(&src));
    time("rust hand-rolled (native)", iters, bytes, || {
        lexwat_test::hand_count(src.as_bytes())
    });
    // ceiling: a tight native byte scan (no lexing) — memory-bandwidth bound
    time("rust byte-sum (native)", iters, bytes, || {
        src.as_bytes().iter().fold(0usize, |a, &b| a + b as usize)
    });

    let engine = Engine::default();
    let mut r_if = wasm_runner(&engine, "lex.wat");
    let mut r_bt = wasm_runner(&engine, "lex_brtable.wat");
    let mut r_nm = wasm_runner(&engine, "lex_nomem.wat");
    let mut r_nb = wasm_runner(&engine, "lex_nomem_brtable.wat");
    time("wasm lex.wat (if-chain)", iters, bytes, || r_if(&src));
    time("wasm lex_brtable.wat", iters, bytes, || r_bt(&src));
    time("wasm lex_nomem.wat", iters, bytes, || r_nm(&src));
    time("wasm lex_nomem_brtable.wat", iters, bytes, || r_nb(&src));

    println!("  -- source in memory, no per-byte boundary crossing --");
    let self_wasm = wat::parse_file(crate_file("lex_selfsource.wat")).unwrap();
    let mut r_self = wasm_mem_runner(&engine, &self_wasm, 1024);
    time("wasm lex_selfsource.wat", iters, bytes, || r_self(&src));
    let self_opt = std::fs::read(out_file("self_opt.wasm")).unwrap();
    let mut r_self_opt = wasm_mem_runner(&engine, &self_opt, 1024);
    time("  + wasm-opt -O3 (inlined)", iters, bytes, || r_self_opt(&src));

    // The wasm-merge output of driver.wat + lex_nomem.wat (generated by build.rs).
    let merged = std::fs::read(out_file("merged.wasm")).unwrap();
    let mut r_merged = wasm_mem_runner(&engine, &merged, 0);
    time("wasm merged (driver+nomem)", iters, bytes, || r_merged(&src));

    println!("  -- whole lex in one call: also internalize the next_token loop --");
    let merged2 = std::fs::read(out_file("merged2.wasm")).unwrap();
    let mut r_merged2 = run_once_runner(&merged2);
    time("wasm merged2 run() one call", iters, bytes, || r_merged2(&src));
    let merged2_opt = std::fs::read(out_file("merged2_opt.wasm")).unwrap();
    let mut r_merged2_opt = run_once_runner(&merged2_opt);
    time("  + wasm-opt -O3 (inlined)", iters, bytes, || r_merged2_opt(&src));

    // Isolate the per-byte host-call overhead: a module that only drains next_byte.
    let probe_wat = r#"(module
        (import "env" "next_byte" (func $nb (result i32)))
        (func (export "reset"))
        (func (export "next_token") (result i32)
          (local $n i32)
          (loop $l (if (i32.ge_s (call $nb) (i32.const 0))
            (then (local.set $n (i32.add (local.get $n) (i32.const 1))) (br $l))))
          (i32.const 0)))"#;
    let wasm = wat::parse_str(probe_wat).unwrap();
    let module = Module::new(&engine, &wasm).unwrap();
    let mut store = Store::new(&engine, Host { src: Vec::new(), idx: 0 });
    let mut linker = Linker::new(&engine);
    linker
        .func_wrap("env", "next_byte", |mut caller: Caller<'_, Host>| -> i32 {
            let h = caller.data_mut();
            match h.src.get(h.idx) {
                Some(&b) => { h.idx += 1; b as i32 }
                None => -1,
            }
        })
        .unwrap();
    let instance = linker.instantiate(&mut store, &module).unwrap();
    let nt = instance.get_typed_func::<(), i32>(&mut store, "next_token").unwrap();
    store.data_mut().src.extend_from_slice(src.as_bytes());
    time("wasm next_byte drain only", iters, bytes, || {
        store.data_mut().idx = 0;
        nt.call(&mut store, ()).unwrap();
        tokens
    });

    // ceiling: a tight in-wasm byte scan over memory (no calls, one bulk write).
    let scan_wat = r#"(module
        (memory (export "memory") 256)
        (global $len (mut i32) (i32.const 0))
        (func (export "set_len") (param $n i32) (global.set $len (local.get $n)))
        (func (export "next_token") (result i32)   ;; sums bytes
          (local $i i32) (local $s i32)
          (loop $l (if (i32.lt_u (local.get $i) (global.get $len))
            (then
              (local.set $s (i32.add (local.get $s) (i32.load8_u (local.get $i))))
              (local.set $i (i32.add (local.get $i) (i32.const 1)))
              (br $l))))
          (local.get $s)))"#;
    let wasm = wat::parse_str(scan_wat).unwrap();
    let module = Module::new(&engine, &wasm).unwrap();
    let mut store = Store::new(&engine, Host { src: Vec::new(), idx: 0 });
    let instance = Linker::new(&engine).instantiate(&mut store, &module).unwrap();
    let mem = instance.get_memory(&mut store, "memory").unwrap();
    let set_len = instance.get_typed_func::<i32, ()>(&mut store, "set_len").unwrap();
    let scan = instance.get_typed_func::<(), i32>(&mut store, "next_token").unwrap();
    mem.write(&mut store, 0, src.as_bytes()).unwrap();
    set_len.call(&mut store, src.len() as i32).unwrap();
    time("wasm byte-scan ceiling", iters, bytes, || {
        scan.call(&mut store, ()).unwrap() as usize
    });
    println!();
}
