//! Differential test: every `lex*.wat` variant's `next_token` stream must match
//! `moss-core`'s logos lexer, across curated cases, all repo `.moss` files, and
//! fuzzed inputs.

use std::path::{Path, PathBuf};

use logos::Logos;
use moss_core::lex::Token;
use wasmtime::*;

/// Host state: the source bytes and a forward-only read cursor for `next_byte`.
struct Host {
    src: Vec<u8>,
    idx: usize,
}

/// The token-id sequence the real lexer produces, using the protocol the WASM
/// modules promise: each token's enum discriminant in order, then `0` (Eof) on
/// success, or `-1` at the first invalid token (mirroring `lex` returning Err).
fn expected(src: &str) -> Vec<i64> {
    let mut out = Vec::new();
    for (result, _range) in Token::lexer(src).spanned() {
        match result {
            Ok(token) => out.push(token as i64),
            Err(_) => {
                out.push(-1);
                return out;
            }
        }
    }
    out.push(Token::Eof as i64); // == 0
    out
}

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .unwrap()
}

/// A `.wat` source that lives alongside this crate.
fn crate_file(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join(name)
}

/// A `.wasm` artifact generated by build.rs into OUT_DIR (via binaryen).
fn out_file(name: &str) -> PathBuf {
    Path::new(env!("OUT_DIR")).join(name)
}

fn module(engine: &Engine, wat_name: &str) -> Module {
    let wasm = wat::parse_file(crate_file(wat_name)).expect("wat should assemble");
    Module::new(engine, &wasm).expect("module should validate")
}

/// Drive the WASM lexer over `src`, returning its emitted token-id sequence.
fn actual(engine: &Engine, module: &Module, src: &str) -> Vec<i64> {
    let mut store = Store::new(
        engine,
        Host {
            src: src.as_bytes().to_vec(),
            idx: 0,
        },
    );
    let mut linker = Linker::new(engine);
    linker
        .func_wrap("env", "next_byte", |mut caller: Caller<'_, Host>| -> i32 {
            let host = caller.data_mut();
            match host.src.get(host.idx) {
                Some(&b) => {
                    host.idx += 1;
                    b as i32
                }
                None => -1,
            }
        })
        .unwrap();
    let instance = linker.instantiate(&mut store, module).unwrap();
    let next_token = instance
        .get_typed_func::<(), i32>(&mut store, "next_token")
        .unwrap();

    let mut out = Vec::new();
    for _ in 0..(src.len() * 2 + 16) {
        let id = next_token.call(&mut store, ()).unwrap() as i64;
        out.push(id);
        if id <= 0 {
            return out; // Eof (0) or invalid (-1)
        }
    }
    panic!("next_token did not terminate for input {src:?}: {out:?}");
}

fn check(engine: &Engine, module: &Module, src: &str) {
    assert_eq!(
        expected(src),
        actual(engine, module, src),
        "mismatch for input {src:?}"
    );
}

/// Recursively collect every `.moss` file under the repo root.
fn moss_files() -> Vec<(PathBuf, String)> {
    fn walk(dir: &Path, out: &mut Vec<(PathBuf, String)>) {
        let Ok(entries) = std::fs::read_dir(dir) else {
            return;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                if path.file_name().is_some_and(|n| n == "target" || n == ".git") {
                    continue;
                }
                walk(&path, out);
            } else if path.extension().is_some_and(|e| e == "moss") {
                if let Ok(text) = std::fs::read_to_string(&path) {
                    out.push((path, text));
                }
            }
        }
    }
    let mut out = Vec::new();
    walk(&repo_root(), &mut out);
    out.sort();
    assert!(!out.is_empty(), "expected to find .moss files");
    out
}

const CURATED: &[&str] = &[
    "",
    "   \t\n\r",
    "# just a comment",
    "# comment\nlet",
    "  # c1\n # c2\n  x  ",
    "a#trailing",
    "! % & ( ) * + , - . / : ; < = > [ ] ^ { | }",
    "!%&()*+,-./:;<=>[]^{|}",
    "!= :: << <= == >= >> ! : < = >",
    "<<=", ">>=", ":::", "====", "!=!", ">><",
    "as assume bind context else fn if import let type use val var while",
    "asx assume_ bindings context1 elsewhere fnx iffy imports lett typed used valid varies whilex",
    "a A _ _x x_ x1 _0 abc123 __init__",
    "0 1 42 0u 7u32 12u64 9i32 3i64 5i 5u 100 -1 -1i32 -2i64 -3 -0u",
    "123u3", "5u68", "5i3", "5i6", "5u32x", "5i320", "9u321", "9u649",
    "-5u", "-5i", "-5i3", "-x", "- 5", "-", "--5", "0u32u",
    "'a' '0' ' ' '\\' '\"' '''",
    "'é' '😀' 'λ' '\u{00a0}'",
    "'ab'", "'é x", "'éé'",
    "\"héllo 😀 λ\"",
    "'", "'a", "'ab'", "''",
    "\"\" \"hello\" \"a b\\tc\" \"q\\\"q\" \"back\\\\slash\" \"\\n\\r\\t\"",
    "\"line\rstill\"",
    "\"unterminated",
    "\"bad\\xescape\"",
    "\"new\nline\"",
    "fn add(x: i32, y: i32) -> i32 { x + y }",
    "let xs = [1, 2, 3]; # list\nval n = 10u32",
    "if a <= b && c >= d { x := 5 } else { y }",
    "import std::io\nuse foo::bar as baz",
    "@", "x @ y", "~", "?", "x ? y", "`", "\\",
    "let'a'\"s\"", "fn0u32if", "x::y::z", "a.b.c",
];

fn run_suite(wat_name: &str) {
    let engine = Engine::default();
    let module = module(&engine, wat_name);

    for src in CURATED {
        check(&engine, &module, src);
    }

    for (path, text) in moss_files() {
        assert_eq!(
            expected(&text),
            actual(&engine, &module, &text),
            "mismatch for moss file {} ({wat_name})",
            path.display()
        );
    }

    // ---- random ASCII fuzz ----
    let charset: &[u8] = b"abxyz_AZ0123459 \t\n\r#!%&()*+,-./:;<=>[]^{|}'\"\\uiUI32649@?~";
    let mut state: u64 = 0x9e37_79b9_7f4a_7c15;
    let mut next = || {
        state = state
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        (state >> 33) as usize
    };
    for _ in 0..12_000 {
        let len = next() % 24;
        let bytes: Vec<u8> = (0..len).map(|_| charset[next() % charset.len()]).collect();
        check(&engine, &module, std::str::from_utf8(&bytes).unwrap());
    }

    // ---- random UTF-8 literal fuzz (char/string contents, interleaved tokens) ----
    let char_scalars = ['a', '0', ' ', '\'', '\\', 'é', '😀', 'λ', '\u{00a0}', 'π', '\n'];
    let str_scalars = ['a', ' ', 'é', '😀', 'λ', '\u{00a0}', 'π', 'b', '9', '\r'];
    let ascii_atoms = ["let", "x", "::", "5u32", "->", "-7i64", "+", "(", ")", "."];
    let mut state: u64 = 0x1234_5678_9abc_def0;
    let mut next = || {
        state = state
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        (state >> 33) as usize
    };
    for _ in 0..7_000 {
        let atoms = 1 + next() % 6;
        let mut src = String::new();
        for _ in 0..atoms {
            match next() % 3 {
                0 => {
                    src.push('\'');
                    src.push(char_scalars[next() % char_scalars.len()]);
                    src.push('\'');
                }
                1 => {
                    src.push('"');
                    for _ in 0..(next() % 4) {
                        src.push(str_scalars[next() % str_scalars.len()]);
                    }
                    src.push('"');
                }
                _ => src.push_str(ascii_atoms[next() % ascii_atoms.len()]),
            }
            src.push(' ');
        }
        check(&engine, &module, &src);
    }
}

#[test]
fn native_hand_lexer() {
    // The native Rust port used in benchmarks must match logos too.
    for src in CURATED {
        assert_eq!(expected(src), lexwat_test::hand_tokens(src.as_bytes()), "{src:?}");
    }
    for (path, text) in moss_files() {
        assert_eq!(
            expected(&text),
            lexwat_test::hand_tokens(text.as_bytes()),
            "moss file {}",
            path.display()
        );
    }
}

#[test]
fn lex_wat() {
    run_suite("lex.wat");
}

#[test]
fn lex_brtable_wat() {
    run_suite("lex_brtable.wat");
}

#[test]
fn lex_nomem_wat() {
    run_suite("lex_nomem.wat");
}

#[test]
fn lex_nomem_brtable_wat() {
    run_suite("lex_nomem_brtable.wat");
}

/// Drive a module that reads its source from memory (host writes it at `offset`,
/// then calls set_len + reset + next_token).
fn actual_mem(engine: &Engine, module: &Module, offset: usize, src: &str) -> Vec<i64> {
    let mut store = Store::new(engine, ());
    let instance = Linker::new(engine)
        .instantiate(&mut store, module)
        .unwrap();
    let memory = instance.get_memory(&mut store, "memory").unwrap();
    memory.write(&mut store, offset, src.as_bytes()).unwrap();
    if let Ok(reset) = instance.get_typed_func::<(), ()>(&mut store, "reset") {
        reset.call(&mut store, ()).unwrap();
    }
    instance
        .get_typed_func::<i32, ()>(&mut store, "set_len")
        .unwrap()
        .call(&mut store, src.len() as i32)
        .unwrap();
    let next_token = instance
        .get_typed_func::<(), i32>(&mut store, "next_token")
        .unwrap();
    let mut out = Vec::new();
    for _ in 0..(src.len() * 2 + 16) {
        let id = next_token.call(&mut store, ()).unwrap() as i64;
        out.push(id);
        if id <= 0 {
            return out;
        }
    }
    panic!("next_token did not terminate for {src:?}: {out:?}");
}

fn run_suite_mem(wasm: &[u8], offset: usize) {
    let engine = Engine::default();
    let module = Module::new(&engine, wasm).unwrap();
    for src in CURATED {
        assert_eq!(expected(src), actual_mem(&engine, &module, offset, src), "{src:?}");
    }
    for (path, text) in moss_files() {
        assert_eq!(
            expected(&text),
            actual_mem(&engine, &module, offset, &text),
            "moss file {}",
            path.display()
        );
    }
}

#[test]
fn lex_selfsource_wat() {
    let wasm = wat::parse_file(crate_file("lex_selfsource.wat")).unwrap();
    run_suite_mem(&wasm, 1024); // source written after the keyword table
}

#[test]
fn merged_driver_nomem() {
    // The wasm-merge output of driver.wat + lex_nomem.wat (driver owns memory @ 0).
    let wasm = std::fs::read(out_file("merged.wasm")).unwrap();
    run_suite_mem(&wasm, 0);
}

/// Drive merged2 (driver2 + lexer): write bytes, run() the whole lex in one
/// call, then read the token ids back out of the second memory.
fn actual_run(engine: &Engine, module: &Module, src: &str) -> Vec<i64> {
    let mut store = Store::new(engine, ());
    let instance = Linker::new(engine).instantiate(&mut store, module).unwrap();
    let bytes = instance.get_memory(&mut store, "bytes").unwrap();
    let toks = instance.get_memory(&mut store, "toks").unwrap();
    bytes.write(&mut store, 0, src.as_bytes()).unwrap();
    instance
        .get_typed_func::<(), ()>(&mut store, "reset")
        .unwrap()
        .call(&mut store, ())
        .unwrap();
    instance
        .get_typed_func::<i32, ()>(&mut store, "set_len")
        .unwrap()
        .call(&mut store, src.len() as i32)
        .unwrap();
    let count = instance
        .get_typed_func::<(), i32>(&mut store, "run")
        .unwrap()
        .call(&mut store, ())
        .unwrap() as usize;
    let mut buf = vec![0u8; count * 4];
    toks.read(&store, 0, &mut buf).unwrap();
    buf.chunks_exact(4)
        .map(|c| i32::from_le_bytes(c.try_into().unwrap()) as i64)
        .collect()
}

#[test]
fn wasm_opt_artifacts_still_correct() {
    // wasm-opt -O3 must not change behavior.
    run_suite_mem(&std::fs::read(out_file("self_opt.wasm")).unwrap(), 1024);

    let mut cfg = Config::new();
    cfg.wasm_multi_memory(true);
    let engine = Engine::new(&cfg).unwrap();
    let module = Module::new(&engine, &std::fs::read(out_file("merged2_opt.wasm")).unwrap()).unwrap();
    for src in CURATED {
        assert_eq!(expected(src), actual_run(&engine, &module, src), "{src:?}");
    }
    for (path, text) in moss_files() {
        assert_eq!(expected(&text), actual_run(&engine, &module, &text), "{}", path.display());
    }
}

#[test]
fn merged2_run_once() {
    let mut config = Config::new();
    config.wasm_multi_memory(true);
    let engine = Engine::new(&config).unwrap();
    let wasm = std::fs::read(out_file("merged2.wasm")).unwrap();
    let module = Module::new(&engine, &wasm).unwrap();
    for src in CURATED {
        assert_eq!(expected(src), actual_run(&engine, &module, src), "{src:?}");
    }
    for (path, text) in moss_files() {
        assert_eq!(
            expected(&text),
            actual_run(&engine, &module, &text),
            "moss file {}",
            path.display()
        );
    }
}
