name: Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  x86_64-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: cachix/install-nix-action@v31
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: actions/checkout@v6
      - run: nix flake check --print-build-logs

      - run: nix build --print-build-logs .#standalone
      - run: cp -RL result moss-linux-x86
      - uses: actions/upload-artifact@v7
        with:
          name: moss-linux-x86
          path: moss-linux-x86

      - run: nix build --print-build-logs .#windows
      - run: cp -RL result moss-windows-x86
      - uses: actions/upload-artifact@v7
        with:
          name: moss-windows-x86
          path: moss-windows-x86

  aarch64-linux:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: cachix/install-nix-action@v31
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: actions/checkout@v6
      - run: nix flake check --print-build-logs

      - run: nix build --print-build-logs .#standalone
      - run: cp -RL result moss-linux-arm
      - uses: actions/upload-artifact@v7
        with:
          name: moss-linux-arm
          path: moss-linux-arm

  aarch64-darwin:
    runs-on: macos-26
    steps:
      - uses: cachix/install-nix-action@v31
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: actions/checkout@v6
      - run: nix flake check --print-build-logs

      - run: nix build --print-build-logs .#standalone
      - run: cp -RL result moss-macos-arm
      - uses: actions/upload-artifact@v7
        with:
          name: moss-macos-arm
          path: moss-macos-arm

  linux-x86:
    needs: x86_64-linux
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v8
        with:
          name: moss-linux-x86
          path: moss
      - run: chmod +x moss/bin/moss
      - run: cp examples/hello.moss moss
      - run: ./moss/bin/moss moss/hello.moss

  linux-arm:
    needs: aarch64-linux
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v8
        with:
          name: moss-linux-arm
          path: moss
      - run: chmod +x moss/bin/moss
      - run: cp examples/hello.moss moss
      - run: ./moss/bin/moss moss/hello.moss

  macos-arm:
    needs: aarch64-darwin
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v8
        with:
          name: moss-macos-arm
          path: moss
      - run: chmod +x moss/bin/moss
      - run: cp examples/hello.moss moss
      - run: ./moss/bin/moss moss/hello.moss

  windows-x86:
    needs: x86_64-linux
    runs-on: windows-2025-vs2026
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v8
        with:
          name: moss-windows-x86
          path: moss
      - run: Copy-Item examples\hello.moss moss
      - run: .\moss\bin\moss.exe moss\hello.moss
