name: CI
on: push
jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build and install
        run: cargo install --path .
      - name: Run hello example
        run: ./hello.qn
