name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  tree-sitter:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: tree-sitter-quench
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm install
      - name: Generate Tree-sitter parser
        run: npx tree-sitter generate
      - name: Test parser
        run: npx tree-sitter test
  rust:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Get dependencies from cache
        uses: Swatinem/rust-cache@v1
      - name: Dry-run publish
        run: cargo publish --dry-run
      - name: Run tests
        run: cargo test
      - name: Install
        run: cargo install --locked --path .
      # partially covered by tests/cli.rs, but this checks the shebang
      - name: Check output of hello example
        run: examples/hello.qn | git diff --no-index examples/hello.txt -
      - name: Upload quench-lsp for next job
        uses: actions/upload-artifact@v2
        with:
          name: quench-lsp
          path: '~/.cargo/bin/quench-lsp'
  vscode:
    needs: rust
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: editors/code
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm install
      - name: Package
        run: npx vsce package
      - name: Download quench-lsp from previous job
        uses: actions/download-artifact@v2
        with:
          name: quench-lsp
      - name: Make quench-lsp executable
        run: |
          chmod +x $GITHUB_WORKSPACE/quench-lsp
          sudo mv $GITHUB_WORKSPACE/quench-lsp /usr/local/bin
      - name: Run tests
        run: xvfb-run -a npm test
