name: CI
on: push
jobs:
  rust:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Tree-sitter CLI
        run: |
          TS_GH=https://github.com/tree-sitter/tree-sitter.git
          cargo install --rev 0.18.0 --git $TS_GH tree-sitter-cli
      - name: Run tests
        run: cargo test
      - name: Install
        run: cargo install --path .
      - name: Check output of hello example
        run: examples/hello.qn | git diff --no-index examples/hello.txt -
  vscode:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: editors/code
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm install
      - name: Compile
        run: npm run compile
      - name: Lint
        run: npm run lint
