name: CI
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: yarn build
      - run: yarn cli
      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/site/dist
          cname: quench-lang.org
      - run: .github/report_git_status.sh

  format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: yarn format
      - run: .github/report_git_status.sh
