name: Publish
on:
  release:
    types:
      - created
jobs:
  crates-io:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Publish
        run: cargo publish --token ${{ secrets.CARGO_TOKEN }}
  vscode-marketplace:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: editors/code
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm install
      - name: Publish
        run: npx vsce publish --baseImagesUrl="https://github.com/quench-lang/quench/raw/${GITHUB_REF#refs/tags/}/editors/code"
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
