name: Update
on:
  schedule:
    - cron: "0 9 * * 6"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  lock:
    runs-on: ubuntu-24.04
    steps:
      - uses: cachix/install-nix-action@v31
      - uses: actions/checkout@v6
      - run: nix flake update 2>&1 | tee nix-flake-update.txt
      - run: nix develop -c bash -c 'rm bun.lock && bun install --lockfile-only'
      - uses: actions/upload-artifact@v7
        with:
          name: lockfiles
          path: |
            flake.lock
            bun.lock
            nix-flake-update.txt

  check:
    needs: lock
    runs-on: ubuntu-24.04
    steps:
      - uses: cachix/install-nix-action@v31
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v8
        with:
          name: lockfiles
      - run: nix flake check --print-build-logs

  pr:
    needs: check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v8
        with:
          name: lockfiles
      - name: Generate pull request body
        id: body
        run: |
          {
            echo 'body<<EOF'
            echo "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
            echo '```'
            cat nix-flake-update.txt
            echo '```'
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"
      - uses: peter-evans/create-pull-request@v8
        with:
          commit-message: Update `flake.lock` and `bun.lock`
          branch: update
          title: Update `flake.lock` and `bun.lock`
          body: ${{ steps.body.outputs.body }}
